"""
routers/reorder.py — /reorder
AI-generated buy list (Screen 3).
Supports fetching today's list and generating a WhatsApp-ready message.
"""

from datetime import date
from fastapi  import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from database import get_db
from models   import ReorderSuggestion
from schemas  import ReorderSuggestionCreate, ReorderSuggestionOut
from auth     import get_current_vendor
from ai.brain import get_brain

router = APIRouter(prefix="/reorder", tags=["Reorder / Buy List"])


@router.get("/", response_model=list[ReorderSuggestionOut],
            summary="Get today's AI reorder suggestions")
def get_reorder(
    for_date: date = None,
    db: Session = Depends(get_db),
    _=Depends(get_current_vendor),
):
    target = for_date or date.today()
    items = (
        db.query(ReorderSuggestion)
        .filter(ReorderSuggestion.for_date == target)
        .order_by(ReorderSuggestion.conf.desc(), ReorderSuggestion.cost.desc())
        .all()
    )
    if not items:
        # Phase 3 brain fills today's buy list on demand.
        get_brain().refresh_reorder_table(db, for_date=target)
        items = (
            db.query(ReorderSuggestion)
            .filter(ReorderSuggestion.for_date == target)
            .order_by(ReorderSuggestion.conf.desc(), ReorderSuggestion.cost.desc())
            .all()
        )
    return items


@router.post("/", response_model=ReorderSuggestionOut, status_code=201,
             summary="Add or refresh a reorder suggestion (called by ML pipeline)")
def create_reorder(
    payload: ReorderSuggestionCreate,
    db: Session = Depends(get_db),
    _=Depends(get_current_vendor),
):
    target = payload.for_date or date.today()
    # Upsert by (name, for_date)
    existing = (
        db.query(ReorderSuggestion)
        .filter(
            ReorderSuggestion.name     == payload.name,
            ReorderSuggestion.for_date == target,
        )
        .first()
    )
    if existing:
        for field, val in payload.model_dump(exclude_none=True).items():
            setattr(existing, field, val)
        db.commit()
        db.refresh(existing)
        return existing

    suggestion = ReorderSuggestion(**payload.model_dump(), for_date=target)
    db.add(suggestion)
    db.commit()
    db.refresh(suggestion)
    return suggestion


@router.delete("/{suggestion_id}", status_code=204,
               summary="Remove a reorder suggestion")
def delete_reorder(
    suggestion_id: int,
    db: Session = Depends(get_db),
    _=Depends(get_current_vendor),
):
    s = db.get(ReorderSuggestion, suggestion_id)
    if not s:
        raise HTTPException(404, "Suggestion not found")
    db.delete(s)
    db.commit()


@router.get("/share", summary="Generate WhatsApp-ready shopping list text")
def share_list(
    for_date: date = None,
    db: Session = Depends(get_db),
    _=Depends(get_current_vendor),
):
    target = for_date or date.today()
    items  = (
        db.query(ReorderSuggestion)
        .filter(ReorderSuggestion.for_date == target)
        .all()
    )
    if not items:
        raise HTTPException(404, "No reorder suggestions for this date")

    lines = [
        f"{i.emoji} {i.name} — {i.qty} kg — ₹{i.cost}" for i in items
    ]
    total = sum(i.cost for i in items)
    msg = (
        f"🌿 VisualAgro Buy List — {target.strftime('%d %b %Y')}\n\n"
        + "\n".join(lines)
        + f"\n\n💰 Total: ₹{total}\n"
        "Projected margin: 42%\n\n"
        "Generated by VisualAgro AI"
    )
    return {"text": msg, "total_cost": total, "item_count": len(items)}
